### PR TITLE
fix hacker news column

### LINKED ISSUE #129: Hackernews links not opening
Lately the app is not able to open hackernews links. Instead it redirects to 
`chrome-extension://kckhddfnffeofnfjcpdffpeiljicclbd/tab.html`

console reads
```js
Uncaught TypeError: Cannot read property 'match' of undefined
    at HTMLElement.attached (tab.js:7182)
    at HTMLElement.attachedCallback (libs.js:9941)
    at HackerNews.Columns.FeedColumn.FeedColumn.draw (main.js:378)
    at HackerNews.Columns.FeedColumn.FeedColumn.render (main.js:469)
    at Tabbie.addColumn (main.js:533)
    at Tabbie.renderColumns (main.js:510)
    at Tabbie.render (main.js:829)
    at main.js:479
    at libs.js:11716
    at flushReadyCallbacks (libs.js:11522)

### PR DESCRIPTION
**Pull request by daxlab**
fixes #129

### CODE REVIEW

**Comment by daxlab** [comment]
@jariz can we push this fix to chrome store ?

**Comment by jariz** [comment]
Can't get gulp to run, will take a look later. (did you get it to run?)

**Comment by daxlab** [comment]
@jariz gulp watch is running .

**Comment by healiha** [comment]
Any idea when this will be pushed to chrome store?

**Comment by daxlab** [comment]
@healiha @jariz api changed again.

**Comment by jariz** [comment]
@healiha when I get it to work locally for me again 😢 
@daxlab Fancy filing a new PR?

**Comment by daxlab** [comment]
@jariz sure. check #131.

**Pull request merged**
