### PR TITLE
change codepen's feed source from 'popular' to 'picks'

### PR DESCRIPTION
**Pull request by syoooo**

### CODE REVIEW

**Comment by syoooo** [comment]
Hi, @jariz , I've changed codepen's feed source.
Wating for merging and release on Chrome webstore~ 😄

**Comment by jariz** [comment]
Maybe add a configuration option so people can decide whether to show popular or picks themselves?
Publishing now..

**Comment by syoooo** [comment]
I've thinked about that but, I found that 'popular' usually not updated several days(display the same thing for around 3 days-), and the quality is also not so good, so maybe only show the 'pick' one is a good chioce.

**Comment by syoooo** [comment]
How do you think?

**Comment by jariz** [comment]
Yea, I guess pick's fine.

**Pull request merged**
