### PR TITLE
Grid of Websites

### PR DESCRIPTION
**Pull request by SebiH**
I needed the same as #74 

I'll probably add more to it, since it's currently basically just a copy&paste from the app column, and the configuration barely has any design.

It looks like this:
image

Configuration: 
image

### CODE REVIEW

**Comment by jariz** [comment]
This is cool! Appreciate the screenshots.
Could be nice to add, but it looks really unpolished sadly.
If I have some time next few weeks, I'll see if I can make it look a bit prettier myself.

**Comment by SebiH** [comment]
I fully agree, the initial version was just to get the functionality in for myself, mostly. Best ignore those two commits, didn't think github would automatically add them to the pullrequest when I push. Oh well. A few more will follow, although I do have to mention I'm by no means a designer.

**Comment by SebiH** [comment]
That should make the config dialog more usable:
config

There are a few things left, such as validation if an entry is completed (or a warning if an entry is incomplete when the dialog is closed), and caching the icons locally.

**Comment by jariz** [comment]
This is really good. I'll make some further changes.

**Comment by michaelowens** [comment]
That's pretty sexy.

**Pull request merged**
