### PR TITLE
fix url for article

### PR DESCRIPTION
**Pull request by daxlab**

### CODE REVIEW

**Comment by daxlab** [comment]
@jariz can we ship this ?

**Comment by momamene** [comment]
I hopefully want this pr to be merged.

**Comment by daxlab** [comment]
> I hopefully want this pr to be merged.

and shipped too.

**Comment by fractaltheory** [comment]
Hi @jariz any news on releasing this update? It's been almost two months. If you need help maintaining the project, I'm sure many of us are willing to provide support.

**edit** P.S. I believe the build is failing because `run-sequence` has a dependency on `chalk` and did not pin the version. The latest `chalk` drops support for Node 0.12, which this project requires. Changing the `run-sequence` dependency to `^2.0.0` should hopefully fix the build. See https://github.com/OverZealous/run-sequence/pull/89 for details.

**Comment by pmig** [comment]
Hi @jariz 

Do you have any news for us? It seems a lot of people use tabbie and would love to see these issues fixed.

**Comment by daxlab** [comment]
Closing this now, since the project has been deprecated.

**Pull request closed without merging**
