### PR TITLE
tabbiehunt v.1

### PR DESCRIPTION
**Pull request by runofthemill**
hi there! I created a column for a visual product hunt. I want to make it more robust and add some features, but I think it's at a point where it's shareable :)

### CODE REVIEW

**Comment by jariz** [comment]
This is cool! Way better overview.
Maybe you can make a setting to enable this in the ProductHunt setting dialog?
Don't really see the point of having two separate columns.

**Comment by runofthemill** [comment]
Good idea! I'll work on that then re-submit. :)

**Comment by jariz** [comment]
Awesome. Can you also rename it back to producthunt again please? :P

**Comment by runofthemill** [comment]
Of course! Just wanted to not confuse people since I was thinking it was going to be separate =D

**Pull request merged**
