### PR TITLE
Added new column for The Verge

### PR DESCRIPTION
**Pull request by kunaldeo**
Added column The Verge.

### CODE REVIEW

**Comment by jariz** [comment]
Hey Kunal, this is cool!
However, The HN column only uses the Panda API because the real HN API is really annoying to work with. I'm still thinking of switching it over to the real API however.
I don't want making use of the Panda API a common thing in Tabbie.
As Tabbie has build-in RSS support, it shouldn't be too hard to switch over to The Verge's real feed (http://www.theverge.com/rss/index.xml)

**Comment by kunaldeo** [comment]
I dont see anything that uses RSS in there. How about I use a Yahoo Pipe ?

**Comment by jariz** [comment]
There are currently no columns that use RSS, but like I said, Tabbie does support it. ([see dataType](https://github.com/jariz/tabbie/blob/master/CONTRIBUTING.md#step-4-get-coding))

**Comment by kunaldeo** [comment]
FeedCoffee XML hardcodes the item node

```
    if @responseType is 'xml'
      parser = new DOMParser
      xmlDoc = parser.parseFromString data, 'text/xml'
      items = xmlDoc.getElementsByTagName 'item'
      data = []
```

How would I override this. 
BTW: Here is the Yahoo pipe I created http://pipes.yahoo.com/pipes/pipe.run?_id=63dacb712b98477f11670fa723466e37&_render=json . I think this will be more elegant.

**Comment by jariz** [comment]
You could probably just add a property to FeedColumn that defaults to 'item' then.  
But you can use the yahoo pipe as well, as long as it isn't the Panda API, it's fine with me.

**Comment by michaelowens** [comment]
@kunaldeo To do that add property, e.g. `xmlTag: 'item'` to FeedColumn.
Then in the snippet you just posted: `items = xmlDoc.getElementsByTagName @xmlTag`
And finally in the Verge class add `xmlTag: 'entry'`.

That way you shouldn't need the yahoo pipe. The more dependencies we would use, the more work it'll become in the future to:
- support all different kinds of feeds
- deal with services closing down

So it's best to always try and work with the native API's rather than via other services or tools.

**Comment by kunaldeo** [comment]
Looks like direct XML request is a no go.
Chrome console reports

```
Fetch API cannot load http://www.theverge.com/rss/index.xml. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://mjeiocbgdlibpfjmnicloaioghcboegk' is therefore not allowed access.
```

**Comment by jariz** [comment]
Yea, then you'll have to ask permission before adding a column.
Quite simple, just add the following to your class, and don't forget to add the url to manifest.json  

``` coffee
  attemptAdd: (successCallback) ->
    chrome.permissions.request
      origins: ['http://theverge.com/']
    , (granted) =>
        if granted and typeof successCallback is 'function' then successCallback()
```

**Comment by kunaldeo** [comment]
It still returns the same error. I think CORS must be enabled on the server side for this to work.

**Comment by jariz** [comment]
Did you do what I asked? Both added the snippet I posted to your class and updated the manifest?
Did you also remove and add the column again afterwards?
If you have permission, you don't need CORS.

**Comment by kunaldeo** [comment]
Thanks for the hint. I missed adding www. That was causing the issue. It is all good now. Your documentation with regards to RSS needs little updating. 
- `dataType` does not have any effect, instead `responseType` needs to be set to XML
- Based on the suggestion from @michaelowens, XML Tag can now be set using `xmlTag` .

**Comment by jariz** [comment]
The RSS stuff is/was still a bit experimental, so sorry for the issues you were having, and thanks for updating it. Merged.

**Pull request merged**
